services:
  - type: web
    name: tik-store-tok-4u-api
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://tik-store-tok-4u.com
    healthCheckPath: /health
    autoDeploy: true
    customDomains:
      - api.tik-store-tok-4u.com
